### ISSUE TITLE
Opinión PBT

### ISSUE THREAD

**Issue by brais2612** [UDC-FIC-VVS/sistema-de-correo-electronico-brais2612#3]
Sobre el PBT de archivador que hice, con un generador, quería saber si va bien enfocado y por qué me da un error la consola, aunque el test pase satisfactoriamente.
 @help_wanted @lauramcastro

**Comment by lauramcastro** [comment]
Ola, Brais: o erro en consola pode depender da túa configuración, de xeito que non sei como reproducilo. Que che di exactamente?

A propiedade que escribes está ben, aínda que son dúas en unha (mellor que as escribas separadas):

- por un lado estás comprobando que para un `ArchivadorSimple` con tamaño "calquera" sempre se vai poder almacenar unha mensaxe con "calquera" texto
- por outro lado estás comprobando que para un `ArchivadorSimple` con tamaño "calquera", o espazo que lle queda despois de almacenar unha mensaxe "calquera" é a resta entre o seu espacio orixinal e o tamaño da mensaxe arquivada

**Comment by brais2612** [comment]
Ola! Sinto estar algo ausente estos dias, estiven cunhas entregas que tiña, agora vou ter mais tempo para dedicarlle a esto,
o que me da a consola é o siguiente :
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.pholser.junit.quickcheck.internal.Reflection (file:/home/brais/.m2/repository/com/pholser/junit-quickcheck-core/0.9.1/junit-quickcheck-core-0.9.1.jar) to field java.lang.reflect.Parameter.index
WARNING: Please consider reporting this to the maintainers of com.pholser.junit.quickcheck.internal.Reflection
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Un saludo e gracias de anteman.

Brais Pérez Busto
________________________________
De: Laura M. Castro <notifications@github.com>
Enviado: domingo, 6 de diciembre de 2020 16:15
Para: UDC-FIC-VVS/sistema-de-correo-electronico-brais2612 <sistema-de-correo-electronico-brais2612@noreply.github.com>
Cc: Brais Pérez Busto <b.perez.busto@udc.es>; Author <author@noreply.github.com>
Asunto: Re: [UDC-FIC-VVS/sistema-de-correo-electronico-brais2612] Opinión PBT (#3)


Ola, Brais: o erro en consola pode depender da túa configuración, de xeito que non sei como reproducilo. Que che di exactamente?

A propiedade que escribes está ben, aínda que son dúas en unha (mellor que as escribas separadas):

  *   por un lado estás comprobando que para un ArchivadorSimple con tamaño "calquera" sempre se vai poder almacenar unha mensaxe con "calquera" texto
  *   por outro lado estás comprobando que para un ArchivadorSimple con tamaño "calquera", o espazo que lle queda despois de almacenar unha mensaxe "calquera" é a resta entre o seu espacio orixinal e o tamaño da mensaxe arquivada

**Comment by lauramcastro** [comment]
Ola @brais2612, desculpa que non puidera volver revisar esta _issue_. Soubeches algo máis ao respecto? 

Se non, e sendo que a propiedade executa correctamente, parecería un erro a _reportar_ aos desenvolvedores, como ben indica o _warning_. A miña aposta é un conflito de versións seguramente.

En todo caso, podes dar esta _issue_ por pechada.
